// All gameplay numbers live here. NEVER generated by an LLM.
// The LLM only picks enums (archetypes, card slots) and writes cosmetic strings.

export type ThemeTag = "fire" | "ice" | "void" | "nature" | "tech" | "stone";
export const THEME_TAGS: ThemeTag[] = ["fire", "ice", "void", "nature", "tech", "stone"];

export const THEME_COLOR: Record<ThemeTag, number> = {
  fire: 0xff5a2a,
  ice: 0x62d8ff,
  void: 0xa96bff,
  nature: 0x5fd86a,
  tech: 0xffd447,
  stone: 0xbfae96,
};

export type Archetype = "swarm" | "fast" | "tank" | "boss";

export interface ArchetypeStats {
  cost: number;
  hp: number;
  speed: number;
  damage: number; // per second of contact
  radius: number;
  scale: number;
  xp: number;
}

export const ARCHETYPES: Record<Archetype, ArchetypeStats> = {
  swarm: { cost: 1, hp: 10, speed: 2.6, damage: 8, radius: 0.5, scale: 0.9, xp: 1 },
  fast: { cost: 2, hp: 14, speed: 4.6, damage: 10, radius: 0.45, scale: 0.8, xp: 2 },
  tank: { cost: 5, hp: 70, speed: 1.7, damage: 18, radius: 0.9, scale: 1.6, xp: 6 },
  boss: { cost: 25, hp: 900, speed: 1.9, damage: 30, radius: 1.8, scale: 3.4, xp: 40 },
};

// Difficulty is a pure function of how deep you are in the tower.
// globalWave = (levelIndex - 1) * WAVES_PER_LEVEL + waveNumber
export const WAVES_PER_LEVEL = 3;

export function globalWave(levelIndex: number, wave: number): number {
  return (levelIndex - 1) * WAVES_PER_LEVEL + wave;
}

export function waveBudget(levelIndex: number, wave: number): number {
  return Math.round(20 * Math.pow(1.18, globalWave(levelIndex, wave) - 1));
}

// Enemy stats scale gently with depth so late levels stay threatening.
export function depthScale(levelIndex: number): number {
  return 1 + (levelIndex - 1) * 0.12;
}

export const WAVE_SPAWN_SECONDS = [26, 32, 20]; // per wave within a level
export const SPAWN_RING_MIN = 18;
export const SPAWN_RING_MAX = 26;
export const ARENA_RADIUS = 34; // gameplay ring; world beyond this is scenery
export const MAX_ENEMIES = 300;

export interface PlayerStats {
  maxHp: number;
  speed: number;
  damage: number;
  attackCooldown: number;
  attackRange: number;
  splashRadius: number;
  pickupRadius: number;
  regen: number; // hp per second
}

export const BASE_PLAYER: PlayerStats = {
  maxHp: 100,
  speed: 7.2,
  damage: 9,
  attackCooldown: 0.55,
  attackRange: 9,
  splashRadius: 0,
  pickupRadius: 3.2,
  regen: 0.4,
};

export type CardSlot = "damage" | "area" | "utility" | "defense";
export const CARD_SLOTS: CardSlot[] = ["damage", "area", "utility", "defense"];

// Fixed stat deltas per slot per tier. Skins only change name/color/description.
export const CARD_TIERS: Record<CardSlot, Array<Partial<PlayerStats>>> = {
  damage: [
    { damage: 5 },
    { damage: 11, attackCooldown: -0.05 },
    { damage: 22, attackCooldown: -0.1 },
  ],
  area: [
    { splashRadius: 1.8 },
    { splashRadius: 2.8, attackRange: 1.5 },
    { splashRadius: 4.2, attackRange: 3 },
  ],
  utility: [
    { speed: 0.8, pickupRadius: 1.5 },
    { speed: 1.4, pickupRadius: 3, attackCooldown: -0.06 },
    { speed: 2.2, pickupRadius: 6, attackCooldown: -0.12 },
  ],
  defense: [
    { maxHp: 25, regen: 0.5 },
    { maxHp: 50, regen: 1.2 },
    { maxHp: 90, regen: 2.4 },
  ],
};

export function xpForLevel(n: number): number {
  return Math.round(5 * Math.pow(1.35, n - 1)) + 3;
}

// Director: nudges spawn rate to absorb variance from generated geometry
// and wildly different player builds. Clamped so it can never break the curve.
export const DIRECTOR = {
  intervalSeconds: 10,
  step: 0.2,
  min: 0.75,
  max: 1.3,
  boredSeconds: 30, // no damage taken this long -> push harder
  panicHpFraction: 0.25, // below this -> ease off
};
