import type { Composition } from "./composer";

/**
 * Optional flavor pass. The deterministic composer already returns a complete,
 * valid Composition; this only rewrites the *wording* (theme name, prompts,
 * card names) to make repeat levels feel less templated.
 *
 * It never returns numbers, archetypes, or slots — those stay exactly as the
 * composer decided. Any failure (no key, bad model id, timeout, malformed
 * JSON) silently keeps the composer's output, so the forge can never break here.
 */

const ENDPOINT = "https://api.openai.com/v1/chat/completions";

interface Flavor {
  theme?: string;
  worldPrompt?: string;
  enemyPrompt?: string;
  monumentPrompt?: string;
  cardNames?: string[];
}

export async function enrich(base: Composition, tally: Record<string, number>): Promise<Composition> {
  const key = process.env.OPENAI_API_KEY;
  if (!key) return base;

  const model = process.env.OPENAI_MODEL ?? "gpt-5.6-luna";
  const votes = Object.entries(tally)
    .filter(([, n]) => n > 0)
    .map(([t, n]) => `${t}:${n}`)
    .join(", ") || "none";

  const system =
    "You write flavor text for a roguelike tower where each level is generated by a " +
    "3D world model. Return ONLY JSON. Keep prompts concrete and physical: describe " +
    "geometry, materials, light and scale, never story or camera moves. Every world " +
    "must have a wide, open, walkable floor because the player fights crowds there.";

  const user = [
    `Players voted for these themes: ${votes}.`,
    `Working theme name: "${base.theme}".`,
    "Rewrite the following into fresher wording for this exact same theme.",
    `worldPrompt: ${base.worldPrompt}`,
    `enemyPrompt: ${base.enemyPrompt}`,
    `monumentPrompt: ${base.monumentPrompt}`,
    `cardNames: ${JSON.stringify(base.cardSkins.map((c) => c.name))}`,
    "",
    "Respond with JSON: {theme, worldPrompt, enemyPrompt, monumentPrompt, cardNames}.",
    `theme: 2-3 words. cardNames: exactly ${base.cardSkins.length} short names, same order.`,
  ].join("\n");

  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 20_000);
    const res = await fetch(ENDPOINT, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` },
      body: JSON.stringify({
        model,
        messages: [
          { role: "system", content: system },
          { role: "user", content: user },
        ],
        response_format: { type: "json_object" },
      }),
      signal: controller.signal,
    });
    clearTimeout(timeout);

    if (!res.ok) {
      console.warn(`enrich: ${model} returned ${res.status}, keeping composed flavor`);
      return base;
    }

    const body = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
    const content = body.choices?.[0]?.message?.content;
    if (!content) return base;

    const flavor = JSON.parse(content) as Flavor;
    return merge(base, flavor);
  } catch (err) {
    console.warn("enrich failed, keeping composed flavor:", err);
    return base;
  }
}

function merge(base: Composition, flavor: Flavor): Composition {
  const str = (v: unknown, fallback: string, max: number) =>
    typeof v === "string" && v.trim().length > 0 ? v.trim().slice(0, max) : fallback;

  const names = Array.isArray(flavor.cardNames) ? flavor.cardNames : [];

  return {
    // Structure is never taken from the model.
    themeTag: base.themeTag,
    composition: base.composition,
    theme: str(flavor.theme, base.theme, 40),
    worldPrompt: str(flavor.worldPrompt, base.worldPrompt, 900),
    enemyPrompt: str(flavor.enemyPrompt, base.enemyPrompt, 400),
    monumentPrompt: str(flavor.monumentPrompt, base.monumentPrompt, 400),
    cardSkins: base.cardSkins.map((skin, i) => ({
      ...skin,
      name: str(names[i], skin.name, 28),
    })),
  };
}
