#!/usr/bin/env bash
# Cache the seed splats locally. Venue wifi is not a dependency worth having
# during a two-minute demo, and local loads are ~10x faster.
set -euo pipefail
BUCKET="https://storage.googleapis.com/forge-dev-public/hackathon-260227"
mkdir -p public/worlds

fetch() { # <local name> <url>
  if [ -s "public/worlds/$1" ]; then
    echo "have $1"
  else
    echo "fetching $1"
    curl -fL --progress-bar "$2" -o "public/worlds/$1.part" && mv "public/worlds/$1.part" "public/worlds/$1"
  fi
}

# The original hackathon samples.
for f in haunted-house.spz cozy_ship.spz cozy_cottage.spz cozy-spaceship_2.spz; do
  fetch "$f" "$BUCKET/$f"
done

# Seeds regenerated by scripts/forge-seeds.ts, once they exist. Their local
# names differ from the samples above, so both sets can sit side by side.
if [ -s scripts/seed-worlds.json ]; then
  node --input-type=commonjs -e '
    const seeds = JSON.parse(require("fs").readFileSync("scripts/seed-worlds.json", "utf8"));
    for (const s of seeds) if (s.splatUrl) console.log(`${s.file}.spz ${s.splatUrl}`);
  ' | while read -r name url; do
    fetch "$name" "$url"
  done
fi

echo "done: $(du -sh public/worlds | cut -f1)"
